apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slskr.fullname" . }}-config
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slskr.fullname" . }}-downloads
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slskr.fullname" . }}-incomplete
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.incomplete.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slskr.fullname" . }}-shares
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.shares.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slskr.fullname" . }}-state
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
