apiVersion: v1
kind: Service
metadata:
  name: {{ include "slskr.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "slskr.name" . }}
  ports:
    - name: http
      port: 5030
      targetPort: http
