import React, { useEffect, useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { isAbortError, requestJson } from '../lib/api';

interface ApiKeysPageProps {
  apiUrl: string;
  apiKey: string | null;
}

interface ApiKey {
  id: string;
  key?: string;
  scopes?: string[];
  created_at?: number;
  expires_at?: number;
  active?: boolean;
}

interface ApiKeyResponse {
  keys?: ApiKey[];
  total?: number;
  mode?: string;
  reason?: string;
}

export default function ApiKeys({ apiUrl, apiKey }: ApiKeysPageProps) {
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [mode, setMode] = useState('static');
  const [reason, setReason] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    let active = true;

    const fetchKeys = async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await requestJson<ApiKeyResponse | ApiKey[]>(`${apiUrl}/api/admin/keys`, apiKey, {
          signal: controller.signal,
        });
        if (!active) return;
        if (Array.isArray(data)) {
          setKeys(data);
          setMode(data.length > 0 ? 'managed' : 'static');
          setReason('');
        } else {
          setKeys(data.keys ?? []);
          setMode(data.mode ?? 'static');
          setReason(data.reason ?? '');
        }
      } catch (fetchError) {
        if (!active || isAbortError(fetchError)) return;
        setError(fetchError instanceof Error ? fetchError.message : 'Failed to fetch API keys');
      } finally {
        if (active) setLoading(false);
      }
    };

    void fetchKeys();
    return () => {
      active = false;
      controller.abort();
    };
  }, [apiUrl, apiKey]);

  const handleCopyKey = async (key: ApiKey) => {
    if (!key.key) return;
    try {
      await navigator.clipboard.writeText(key.key);
      setCopiedId(key.id);
      window.setTimeout(() => setCopiedId(null), 2000);
    } catch {
      setError('Unable to copy the API key');
    }
  };

  const formatDate = (timestamp?: number) => {
    if (!timestamp) return 'Unknown';
    return new Date(timestamp * 1000).toLocaleDateString();
  };

  if (loading) {
    return <div className="text-center text-gray-500">Loading API keys...</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900">API authentication</h2>
        <p className="mt-1 text-sm text-gray-600">
          Authentication is configured on the daemon, not generated by this dashboard.
        </p>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-red-800">{error}</p>
        </div>
      )}

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
        <h3 className="text-lg font-semibold text-blue-900">{mode === 'static' ? 'Static token authentication' : 'Managed API keys'}</h3>
        <p className="text-blue-800 mt-2">
          {reason || 'Use the configured SLSKR_API_TOKEN (or a configured ApiKey credential) in the dashboard settings.'}
        </p>
        <p className="text-sm text-blue-700 mt-3">
          The token value is never returned by the daemon and is not displayed here.
        </p>
      </div>

      {keys.length > 0 && (
        <div className="bg-white rounded-lg shadow overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">ID</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">Scopes</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">Created</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">Expires</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">Status</th>
                  <th className="px-6 py-3 text-left text-sm font-semibold text-gray-900">Secret</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {keys.map((key) => (
                  <tr key={key.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4">
                      <code className="text-sm bg-gray-100 px-2 py-1 rounded">{key.id}</code>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-600">{(key.scopes ?? []).join(', ') || 'Unknown'}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{formatDate(key.created_at)}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{key.expires_at ? formatDate(key.expires_at) : 'Never'}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{key.active === false ? 'Revoked' : 'Active'}</td>
                    <td className="px-6 py-4">
                      {key.key && (
                        <button
                          onClick={() => void handleCopyKey(key)}
                          className="p-2 hover:bg-gray-100 rounded text-gray-600"
                          aria-label={`Copy key ${key.id}`}
                        >
                          {copiedId === key.id ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
