apiVersion: v1
kind: ServiceAccount
metadata:
  name: slskr
  namespace: soulseekr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slskr
  namespace: soulseekr
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slskr
  namespace: soulseekr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slskr
subjects:
- kind: ServiceAccount
  name: slskr
  namespace: soulseekr
