#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExperiencePreference {
    pub default_value: &'static str,
    pub group: &'static str,
    pub id: &'static str,
    pub input: &'static str,
    pub label: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AutomationRecipe {
    pub approval_gate: &'static str,
    pub cadence: &'static str,
    pub cooldown: &'static str,
    pub description: &'static str,
    pub enabled_by_default: bool,
    pub file_impact: &'static str,
    pub id: &'static str,
    pub max_run_time: &'static str,
    pub network_impact: &'static str,
    pub title: &'static str,
}

pub const fn experience_preferences() -> &'static [ExperiencePreference] {
    &[
        ExperiencePreference {
            default_value: "balanced",
            group: "Search",
            id: "searchRankingProfile",
            input: "text",
            label: "Ranking Profile",
        },
        ExperiencePreference {
            default_value: "lossless",
            group: "Search",
            id: "searchPreferredCondition",
            input: "text",
            label: "Preferred Condition",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Search",
            id: "searchDuplicateFolding",
            input: "checkbox",
            label: "Fold duplicate results",
        },
        ExperiencePreference {
            default_value: "detailed",
            group: "Search",
            id: "searchActionPreviewDensity",
            input: "text",
            label: "Action Preview Density",
        },
        ExperiencePreference {
            default_value: "current",
            group: "Player",
            id: "playerRadioSeedMode",
            input: "text",
            label: "Radio Seed",
        },
        ExperiencePreference {
            default_value: "manual",
            group: "Player",
            id: "playerScrobbleMode",
            input: "text",
            label: "Scrobble Mode",
        },
        ExperiencePreference {
            default_value: "last",
            group: "Player",
            id: "playerDefaultVisualizer",
            input: "text",
            label: "Default Visualizer",
        },
        ExperiencePreference {
            default_value: "false",
            group: "Player",
            id: "playerQueueAutoFill",
            input: "checkbox",
            label: "Enable queue auto-fill",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Player",
            id: "playerShowRatings",
            input: "checkbox",
            label: "Show ratings",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Player",
            id: "playerCaptureHistory",
            input: "checkbox",
            label: "Capture history",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Player",
            id: "playerKeyboardShortcuts",
            input: "checkbox",
            label: "Keyboard shortcuts",
        },
        ExperiencePreference {
            default_value: "all",
            group: "Discovery",
            id: "discoveryApprovalFilter",
            input: "text",
            label: "Approval Filter",
        },
        ExperiencePreference {
            default_value: "0.70",
            group: "Discovery",
            id: "discoveryConfidenceFloor",
            input: "text",
            label: "Confidence Floor",
        },
        ExperiencePreference {
            default_value: "14",
            group: "Discovery",
            id: "discoveryStaleDays",
            input: "text",
            label: "Stale Days",
        },
        ExperiencePreference {
            default_value: "false",
            group: "Messages",
            id: "messagesDenseMode",
            input: "checkbox",
            label: "Dense mode",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Messages",
            id: "messagesPinnedRestore",
            input: "checkbox",
            label: "Restore pinned conversations",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Messages",
            id: "messagesUnreadBadges",
            input: "checkbox",
            label: "Unread badges",
        },
        ExperiencePreference {
            default_value: "true",
            group: "Messages",
            id: "messagesSearchEnabled",
            input: "checkbox",
            label: "Message search",
        },
    ]
}

pub const fn automation_recipes() -> &'static [AutomationRecipe] {
    &[
        AutomationRecipe {
            approval_gate: "None required",
            cadence: "Continuous",
            cooldown: "5 minutes",
            description: "Checks connection, shares, paths, and credentials for setup drift.",
            enabled_by_default: true,
            file_impact: "Read only",
            id: "local-diagnostics",
            max_run_time: "30 seconds",
            network_impact: "Local",
            title: "Local Diagnostics",
        },
        AutomationRecipe {
            approval_gate: "None required",
            cadence: "Daily",
            cooldown: "24 hours",
            description:
                "Surfaces stale share-cache and library-scan reminders before users hit missing results.",
            enabled_by_default: true,
            file_impact: "Read only",
            id: "stale-cache-reminders",
            max_run_time: "1 minute",
            network_impact: "Local",
            title: "Share and Library Reminders",
        },
        AutomationRecipe {
            approval_gate: "None required",
            cadence: "Every 15 minutes",
            cooldown: "15 minutes",
            description: "Keeps local dashboard summaries fresh without contacting public peers.",
            enabled_by_default: true,
            file_impact: "Read only",
            id: "dashboard-refresh",
            max_run_time: "20 seconds",
            network_impact: "Local",
            title: "Dashboard Refresh",
        },
        AutomationRecipe {
            approval_gate: "Download approval",
            cadence: "Manual or scheduled",
            cooldown: "2 hours",
            description: "Retries failed Wishlist items using the selected acquisition profile.",
            enabled_by_default: false,
            file_impact: "Downloads after approval",
            id: "wishlist-retry",
            max_run_time: "20 minutes",
            network_impact: "Public peers possible",
            title: "Wishlist Retry",
        },
        AutomationRecipe {
            approval_gate: "Fix confirmation",
            cadence: "Manual or scheduled",
            cooldown: "24 hours",
            description: "Finds duplicates, dead files, metadata gaps, fake lossless files, and missing art.",
            enabled_by_default: false,
            file_impact: "Read only until fixed",
            id: "library-health-scan",
            max_run_time: "30 minutes",
            network_impact: "Local",
            title: "Library Health Scan",
        },
        AutomationRecipe {
            approval_gate: "Configured import success",
            cadence: "After import",
            cooldown: "10 minutes",
            description: "Asks configured media servers to rescan after successful library imports.",
            enabled_by_default: false,
            file_impact: "Media-server scan",
            id: "media-server-rescan",
            max_run_time: "2 minutes",
            network_impact: "Local network",
            title: "Media Server Rescan",
        },
        AutomationRecipe {
            approval_gate: "Explicit evidence publication opt-in",
            cadence: "Manual or scheduled",
            cooldown: "12 hours",
            description:
                "Publishes explicit opt-in signed quality and verification evidence to trusted mesh peers.",
            enabled_by_default: false,
            file_impact: "No file writes",
            id: "mesh-evidence-publish",
            max_run_time: "10 minutes",
            network_impact: "Trusted mesh",
            title: "Mesh Evidence Publish",
        },
    ]
}
