use super::*;

pub(in crate::cli) fn incoming_connection_name<S>(
    incoming: &IncomingConnection<S>,
) -> &'static str {
    match incoming {
        IncomingConnection::PeerMessages(_) => "peer_messages",
        IncomingConnection::ObfuscatedPeerMessages(_) => "obfuscated_peer_messages",
        IncomingConnection::FileTransfer(_) => "file_transfer",
        IncomingConnection::Distributed(_) => "distributed",
        IncomingConnection::PeerInit { .. } => "peer_init",
        IncomingConnection::PierceFirewall { .. } => "pierce_firewall",
        IncomingConnection::UnknownInit { .. } => "unknown_init",
    }
}

pub(super) fn server_message_name(message: &ServerMessage) -> &'static str {
    match message {
        ServerMessage::LoginRequest(_) => "login_request",
        ServerMessage::LoginResponse(_) => "login_response",
        ServerMessage::SetWaitPort(_) => "set_wait_port",
        ServerMessage::GetPeerAddressRequest { .. } => "get_peer_address_request",
        ServerMessage::GetPeerAddressResponse(_) => "get_peer_address_response",
        ServerMessage::WatchUserRequest { .. } => "watch_user_request",
        ServerMessage::WatchUserResponse(_) => "watch_user_response",
        ServerMessage::UnwatchUser { .. } => "unwatch_user",
        ServerMessage::GetUserStatusRequest { .. } => "get_user_status_request",
        ServerMessage::GetUserStatusResponse(_) => "get_user_status_response",
        ServerMessage::IgnoreUser { .. } => "ignore_user",
        ServerMessage::UnignoreUser { .. } => "unignore_user",
        ServerMessage::SayChatroomRequest { .. } => "say_chatroom_request",
        ServerMessage::SayChatroomResponse { .. } => "say_chatroom_response",
        ServerMessage::ConnectToPeerRequest(_) => "connect_to_peer_request",
        ServerMessage::ConnectToPeerResponse(_) => "connect_to_peer_response",
        ServerMessage::MessageUserRequest { .. } => "message_user_request",
        ServerMessage::MessageUserResponse(_) => "message_user_response",
        ServerMessage::MessageAcked { .. } => "message_acked",
        ServerMessage::FileSearchRequest(_) => "file_search_request",
        ServerMessage::FileSearchIncoming { .. } => "file_search_incoming",
        ServerMessage::JoinRoom { .. } => "join_room",
        ServerMessage::JoinedRoom(_) => "joined_room",
        ServerMessage::UserJoinedRoom { .. } => "user_joined_room",
        ServerMessage::UserLeftRoom { .. } => "user_left_room",
        ServerMessage::LeaveRoom { .. } => "leave_room",
        ServerMessage::SetStatus { .. } => "set_status",
        ServerMessage::ServerPing => "server_ping",
        ServerMessage::SharedFoldersFiles { .. } => "shared_folders_files",
        ServerMessage::GetUserStatsRequest { .. } => "get_user_stats_request",
        ServerMessage::GetUserStats { .. } => "get_user_stats",
        ServerMessage::GetUserInterestsRequest { .. } => "get_user_interests_request",
        ServerMessage::UserInterests(_) => "user_interests",
        ServerMessage::Relogged => "relogged",
        ServerMessage::UserSearch(_) => "user_search",
        ServerMessage::RecommendationsRequest { .. } => "recommendations_request",
        ServerMessage::RecommendationsResponse { .. } => "recommendations_response",
        ServerMessage::AddThingILike { .. } => "add_thing_i_like",
        ServerMessage::RemoveThingILike { .. } => "remove_thing_i_like",
        ServerMessage::GlobalAdminMessage { .. } => "global_admin_message",
        ServerMessage::RoomListRequest => "room_list_request",
        ServerMessage::RoomList(_) => "room_list",
        ServerMessage::AddPrivilegedUser { .. } => "add_privileged_user",
        ServerMessage::PrivilegedUsers(_) => "privileged_users",
        ServerMessage::HaveNoParent { .. } => "have_no_parent",
        ServerMessage::ParentMinSpeed { .. } => "parent_min_speed",
        ServerMessage::ParentSpeedRatio { .. } => "parent_speed_ratio",
        ServerMessage::ParentInactivityTimeout { .. } => "parent_inactivity_timeout",
        ServerMessage::SearchInactivityTimeout { .. } => "search_inactivity_timeout",
        ServerMessage::MinParentsInCache { .. } => "min_parents_in_cache",
        ServerMessage::DistribPingInterval { .. } => "distributed_ping_interval",
        ServerMessage::ParentIp { .. } => "parent_ip",
        ServerMessage::CheckPrivilegesRequest => "check_privileges_request",
        ServerMessage::CheckPrivilegesResponse { .. } => "check_privileges_response",
        ServerMessage::AcceptChildren { .. } => "accept_children",
        ServerMessage::EmbeddedMessage { .. } => "embedded_message",
        ServerMessage::PossibleParents(_) => "possible_parents",
        ServerMessage::WishlistSearch(_) => "wishlist_search",
        ServerMessage::WishlistInterval { .. } => "wishlist_interval",
        ServerMessage::SimilarUsersRequest => "similar_users_request",
        ServerMessage::SimilarUsers(_) => "similar_users",
        ServerMessage::ItemRecommendationsRequest { .. } => "item_recommendations_request",
        ServerMessage::ItemRecommendations(_) => "item_recommendations",
        ServerMessage::ItemSimilarUsersRequest { .. } => "item_similar_users_request",
        ServerMessage::ItemSimilarUsers(_) => "item_similar_users",
        ServerMessage::RoomTickers { .. } => "room_tickers",
        ServerMessage::RoomTickerAdded { .. } => "room_ticker_added",
        ServerMessage::RoomTickerRemoved { .. } => "room_ticker_removed",
        ServerMessage::RoomSearch(_) => "room_search",
        ServerMessage::SendUploadSpeed { .. } => "send_upload_speed",
        ServerMessage::UserPrivilegesRequest { .. } => "user_privileges_request",
        ServerMessage::UserPrivilege { .. } => "user_privilege",
        ServerMessage::GivePrivileges { .. } => "give_privileges",
        ServerMessage::BranchLevel { .. } => "branch_level",
        ServerMessage::BranchRoot { .. } => "branch_root",
        ServerMessage::ChildDepth { .. } => "child_depth",
        ServerMessage::ResetDistributed => "reset_distributed",
        ServerMessage::PrivateRoomUsers { .. } => "private_room_users",
        ServerMessage::PrivateRoomAddUser { .. } => "private_room_add_user",
        ServerMessage::PrivateRoomRemoveUser { .. } => "private_room_remove_user",
        ServerMessage::PrivateRoomDropMembership { .. } => "private_room_drop_membership",
        ServerMessage::PrivateRoomDropOwnership { .. } => "private_room_drop_ownership",
        ServerMessage::PrivateRoomAdded { .. } => "private_room_added",
        ServerMessage::PrivateRoomRemoved { .. } => "private_room_removed",
        ServerMessage::PrivateRoomToggle { .. } => "private_room_toggle",
        ServerMessage::ChangePassword { .. } => "change_password",
        ServerMessage::PrivateRoomAddOperator { .. } => "private_room_add_operator",
        ServerMessage::PrivateRoomRemoveOperator { .. } => "private_room_remove_operator",
        ServerMessage::PrivateRoomOperatorAdded { .. } => "private_room_operator_added",
        ServerMessage::PrivateRoomOperatorRemoved { .. } => "private_room_operator_removed",
        ServerMessage::PrivateRoomOwned { .. } => "private_room_owned",
        ServerMessage::MessageUsers { .. } => "message_users",
        ServerMessage::JoinGlobalRoom => "join_global_room",
        ServerMessage::LeaveGlobalRoom => "leave_global_room",
        ServerMessage::GlobalRoomMessage { .. } => "global_room_message",
        ServerMessage::ExcludedSearchPhrases(_) => "excluded_search_phrases",
        ServerMessage::AddThingIHate { .. } => "add_thing_i_hate",
        ServerMessage::RemoveThingIHate { .. } => "remove_thing_i_hate",
        ServerMessage::CantConnectToPeerRequest { .. } => "cant_connect_to_peer_request",
        ServerMessage::CantConnectToPeerResponse { .. } => "cant_connect_to_peer_response",
        ServerMessage::CantCreateRoom { .. } => "cant_create_room",
        ServerMessage::CantJoinRoom { .. } => "cant_join_room",
        ServerMessage::SetRoomTicker { .. } => "set_room_ticker",
        ServerMessage::NotifyPrivileges { .. } => "notify_privileges",
        ServerMessage::AckNotifyPrivileges { .. } => "ack_notify_privileges",
        ServerMessage::Unknown { .. } => "unknown",
    }
}

pub(in crate::cli) fn peer_message_name(message: &PeerMessage) -> &'static str {
    match message {
        PeerMessage::PrivateMessage(_) => "private_message",
        PeerMessage::GetShareFileList => "get_share_file_list",
        PeerMessage::SharedFileListResponse(_) => "shared_file_list_response",
        PeerMessage::FileSearchRequest { .. } => "file_search_request",
        PeerMessage::FileSearchResponse(_) => "file_search_response",
        PeerMessage::RoomInvitation(_) => "room_invitation",
        PeerMessage::CancelledQueuedTransfer(_) => "cancelled_queued_transfer",
        PeerMessage::UserInfoRequest => "user_info_request",
        PeerMessage::UserInfoResponse(_) => "user_info_response",
        PeerMessage::SendConnectToken(_) => "send_connect_token",
        PeerMessage::MoveDownloadToTop(_) => "move_download_to_top",
        PeerMessage::FolderContentsRequest(_) => "folder_contents_request",
        PeerMessage::FolderContentsResponse(_) => "folder_contents_response",
        PeerMessage::TransferRequest(_) => "transfer_request",
        PeerMessage::TransferResponse(_) => "transfer_response",
        PeerMessage::PlaceholdUpload { .. } => "placehold_upload",
        PeerMessage::QueueUpload { .. } => "queue_upload",
        PeerMessage::PlaceInQueueResponse { .. } => "place_in_queue_response",
        PeerMessage::UploadFailed { .. } => "upload_failed",
        PeerMessage::ExactFileSearchRequest(_) => "exact_file_search_request",
        PeerMessage::QueuedDownloads(_) => "queued_downloads",
        PeerMessage::IndirectFileSearchRequest(_) => "indirect_file_search_request",
        PeerMessage::UploadDenied { .. } => "upload_denied",
        PeerMessage::PlaceInQueueRequest { .. } => "place_in_queue_request",
        PeerMessage::UploadQueueNotification => "upload_queue_notification",
        PeerMessage::Unknown { .. } => "unknown",
    }
}
